### ISSUE TITLE
undefined symbol dest on line 96046

### ISSUE THREAD

**Issue by maymatxacamtay** [nSystemz/Nemesus-Roleplay-Legacy#10]
`NemesusRoleplay.pwn(196518) : warning 208: function with tag result used before definition, forcing reparse
NemesusRoleplay.pwn(96046) : error 017: undefined symbol "dest"
NemesusRoleplay.pwn(96049) : error 017: undefined symbol "dest"
NemesusRoleplay.pwn(96049) : warning 215: expression has no effect
NemesusRoleplay.pwn(96049) : error 001: expected token: ";", but found "]"
NemesusRoleplay.pwn(96049) : error 029: invalid expression, assumed zero
NemesusRoleplay.pwn(96049) : fatal error 107: too many error messages on one line`

**Comment by maymatxacamtay** [comment]
![image](https://github.com/nSystemz/Nemesus-Roleplay/assets/121553953/f9315531-de97-4203-b2a1-4ec071622eb0)

**Comment by maymatxacamtay** [comment]
![image](https://github.com/nSystemz/Nemesus-Roleplay/assets/121553953/80d1b3a1-fb17-4b54-bc3e-6b8caa4c6a43)
while compile on Pawn

**Comment by nSystemz** [comment]
It seems, youre not using the correct includes. Try to use the includes, we included in the download package. Also use the right Pawno which is linked to the right include directory

**Comment by maymatxacamtay** [comment]
okay thanks!
