### ISSUE TITLE
SQL Anzahl der Felder stimmt nicht mit der Anzahl der Werte in Zeile 1 überein

### ISSUE THREAD

**Issue by basecore1337** [nSystemz/Nemesus-Roleplay-Legacy#11]
--
-- Daten für Tabelle `characters`
--

INSERT INTO `characters` (`id`, `userid`, `name`, `json`, `cash`, `birth`, `bank`, `size`, `eyecolor`, `job`, `minijob`, `lastonline`, `licenses`, `education`, `origin`, `skills`, `appearance`, `gender`, `faction`, `rang`, `faction_dutytime`, `faction_since`, `last_spawn`, `ucp_privat`, `ck`, `mygroup`, `closed`, `tutorialstep`, `health`, `armor`, `thirst`, `hunger`, `screen`, `lastpos`, `items`, `inhouse`, `defaultbank`, `online`, `truckerskill`, `nextpayday`, `payday_points`, `sellprods`, `abusemoney`, `lastsmartphone`, `thiefskill`, `fishingskill`, `busskill`, `farmingskill`, `animations`, `walkingstyle`, `clothing`, `factionduty`, `sapoints`, `swat`, `arrested`, `cell`, `dutyjson`, `death`, `disease`, `craftingskill`, `robcooldown`, `adcount`, `guessvalue`, `jobless`, `friends`) VALUES
(1, 1, 'Test Char', '{\"birth\":\"22.10.1991\",\"origin\":\"Los Santos\",\"hair\":[1,16,0],\"beard\":[255,0],\"blendData\":[12,0,0,0,0,0],\"faceFeatures\":[0.[...]

MySQL meldet: Dokumentation
#1136 - Anzahl der Felder stimmt nicht mit der Anzahl der Werte in Zeile 1 überein

**Comment by Crafti1995** [comment]
Moin, 

die beschriebene characters Tabelle gehört zum RageMP Gamemode, nicht zum SAMP Gamemode. Es fehlt nach friends das Feld petname.

Mit freundlichen Grüßen

**Comment by nSystemz** [comment]
Falsches Repo, aber der Fehler wurde im anderen Repo behoben.
