### ISSUE TITLE
Fehler bei speichern im Datenbank

### ISSUE THREAD

**Issue by ShadowKev1999** [nSystemz/Nemesus-Roleplay-Legacy#12]
Guten Tag.

Mir ist aufgefallen das beipsiel bei den Roleplay name angeben beispiel (Max_Mustermann) das steht Vorname_Nachname_36

das stimmt was nicht.

ich benutze plesk mit mariadb(phpmyadmin)

**Comment by nSystemz** [comment]
Ein solcher Fehler ist mir beim testen nicht aufgefallen, bitte schaue dir auch die Readme Hinweise an.
