### ISSUE TITLE
Datenbank fraktionsfahrzeuge fehlt

### ISSUE THREAD

**Issue by Jens2222** [nSystemz/Nemesus-Roleplay-Legacy#2]
wenn man fraktionsfahrzeuge erstellen will fällt einen auf das fraktionsfahrzeuge für die datenbank fehlt :)

**Comment by Spaex** [comment]
Im File `nrp.sql` existiert die Tabellenstruktur für fraktionsfahrzeuge und wird dementsprechend erzeugt. 
Du kannst die Fraktionsfahrzeuge dann via `/cfc` auf dem Gameserver erstellen. 
Vielleicht hast du dich ja beim importieren vertan o.ä.
