### ISSUE TITLE
Bug Krankenhaus

### ISSUE THREAD

**Issue by DJNK01** [nSystemz/Nemesus-Roleplay-Legacy#3]
Wenn man stirbt, dann kommt man auf der Schleife der public Nachbehandlug2 nicht mehr raus. "Die Behandlung war kostenlos, leider dürfen sie noch nicht gehen". Man bleibt in dem Raum gefangen und es passiert nichts mehr. Ebenfalls wird das Geld auf 0 gesetzt und nicht mehr zurückgegeben, was man bei sich trägt

**Comment by Spaex** [comment]
Hi, 

da scheint es sich lediglich um einen Fehler im Text zu handeln.
Eigentlich sollte es heißen `Die Behandlung war kostenlos da sie eine Krankenversicherung haben, sie dürfen jetzt gehen!`
Du kannst trotzdem via `/sa` die Animation beenden und gehen. Ggf. wäre ein entsprechender OOC-Hinweis hier sinnvoll. 
Das werde ich heute Abend oder spätestens morgen ausbessern und dann in die Repo pushen und dich hier darüber informieren. 
Das Geld sollst du jedoch verlieren. Sobald du stirbst und dann nach einer Minute dich entscheidest dich ins Krankenhaus transportieren zu lassen über die Option Handlungsunfähig verlierst du dein Geld an dem Ort wo du gestorben bist (wird dort gedroppt). Dies kannst du lediglich verhindern wenn dich ein Sanitäter wiederbelebt. 

MfG Spaex
