### ISSUE TITLE
FrakCars

### ISSUE THREAD

**Issue by DJNK01** [nSystemz/Nemesus-Roleplay-Legacy#4]
Wenn man ein Frakcar erstellt, dann kann man nicht damit fahren, da der Tank leer ist.  Lässt sich aber auch nicht mit /refillfc. Bei einem Serverneustadt ist auch eine Autokralle dran mit dem Grund . NULL - Bitte rufe die SOD

**Comment by Spaex** [comment]
Fahrzeuge werden ohne vollen Tank erstellt da jedes Fahrzeug ein unterschiedliches Tankvolumen hat. 
Alternativ kannst du die Tankmenge in **Zeile 32605** anpassen oder du nutzt beim Erstellen zusätzlich noch den Befehl `/fillveh`. 
Du kannst aber auch nach dem Erstellen einer größerer Menge an Fraktionsfahrzeugen den von dir genannten Befehl benutzen. 
Da bekomme ich aber deinen Fehler nicht reproduziert. Bei mir erfüllt `/refillfc` den gewünschten Effekt und betankt alle Fraktionsfahrzeuge. 
![sa-mp-449 (2)](https://user-images.githubusercontent.com/46825907/185797448-e7000b29-f950-4f72-83cf-a26dba9607bf.png)

Auch das mit der Parkkralle bekomme ich nicht reproduziert. Bei mir hat kein Fahrzeug (bei ca 100 Fraktionsfahrzeugen) nach einem Restart (mehrfach probiert) eine Autokralle. 
Kannst du nochmal probieren den Fehler reproduzieren und mir dann sagen wie du ihn reproduziert hast?

**Auch wichtig:** Erstelle keine Firma mit der FirmenID 0 und einer Abschlepplizenz. Das sorgt für Konflikte mit der POD Fraktion.

**Comment by DJNK01** [comment]
mega. vielen dank für deine Riesen Hilfe.  Bei mir stehen keinerlei Fraktionsfahrzeuge im Server.  ist es möglich deine SQL Datei zu bekommen, in der schon alle Fraktioncars stehen ?

**Comment by Spaex** [comment]
Gerne. 
Ich hab lediglich grad für Testzwecke ~100 Clover erstellt und sie allen verschiedenen Fraktion zugeordnet. 
Ich glaub kaum dass dir 100 Clover in San Andreas verteilt etwas helfen. 
Eine DB mit sinnvollen Fraktionsfahrzeugen habe ich nicht.
Aber die kann man sich relativ schnell selbst erstellen InGame.

Konntest du den Fehler mit der Kralle nochmal reproduzieren?

**Comment by Spaex** [comment]
Aufgrund fehlender Rückmeldung geh ich davon aus, dass du den Fehler nicht reproduzieren konntest. 
Ich habs auch noch mal mit 100 Fahrzeugen probiert und konnte ihn nicht reproduzieren. Dementsprechend scheint es sich hier um keinen Fehler in der Repository hier zu handeln.
