### ISSUE TITLE
Zeitungsservice nExpress 

### ISSUE THREAD

**Issue by DJNK01** [nSystemz/Nemesus-Roleplay-Legacy#5]
Wenn man mit /work den Job startet, dann kann man keine anderen Befehle mehr verwenden.  einzige Nachricht bei allen Befehlen ist Unknown Command

**Comment by Spaex** [comment]
Ich kann deinen Fehler leider nicht reproduzieren.
Check mal deinen server.log ab ob auch wirklich alles richtig lädt bzw. lade ihn hier hoch, dann werfe ich mal einen Blick darauf.
Bei meinem Versuch das zu reproduzieren funktionieren alle Befehle noch, nachdem ich via /work als Zeitungsjunge arbeiten gegangen bin. 
![sa-mp-450](https://user-images.githubusercontent.com/46825907/185797603-a8a97c87-202a-4ad1-826a-359d38cd538a.png)
Siehe hier am Beispiel mit `/call` und `/help`.

**Comment by DJNK01** [comment]
Gibt es eine Möglichkeit mit dir mal im TS / Discord zu quatschen ? Hätte ein paar Fragen an dich

**Comment by DJNK01** [comment]
[server_log.txt](https://github.com/nSystemz/Nemesus-Roleplay/files/9389419/server_log.txt)

Das ist meine Server Log.

**Comment by Spaex** [comment]
Kannst mir deine Fragen gerne via Discord zukommen lassen.

Bist du dem Installationsvideo auch komplett gefolgt? Bzw. hast du auch den Downloadserver für die models eingerichtet? So dass der Server auch alle Custom Objekte ziehen kann? 
https://www.youtube.com/watch?v=tMi-777Xw4w

**Comment by DJNK01** [comment]
Ich bin im Discord Unter DJNK und habe dir mal eine Freundschaftanfrage geschickt damit ich dir die Fragen da schreiben kann
