### ISSUE TITLE
Ladefehler Objekte Stadthalle

### ISSUE THREAD

**Issue by DJNK01** [nSystemz/Nemesus-Roleplay-Legacy#6]
![Screenshot 2022-08-21 at 14 05 50](https://user-images.githubusercontent.com/111686376/185792324-a50956a5-6493-4eee-8596-1f2c75540b41.png)
![Screenshot 2022-08-21 at 14 05 57](https://user-images.githubusercontent.com/111686376/185792326-8f8b807b-6c01-40a6-90e2-0d047e4a2e36.png)

**Comment by Spaex** [comment]
Ich konnte diesen Fehler ebenfalls nicht reproduzieren.
Die More-Maps.amx (welche auch die Stadthalle enthält) hier in der Github Repo funktioniert einwandfrei und lädt die Stadthallen Map ohne Fehler.
Dementsprechend ist es kein Fehler in der Repo. 
Siehe hier: 
![sa-mp-451](https://user-images.githubusercontent.com/46825907/185798137-b05b0c2a-696b-4c23-8bab-741740ecf579.png)
![sa-mp-452](https://user-images.githubusercontent.com/46825907/185798143-74842125-296f-4f4e-b3e8-9784a8a64fa8.png)

Ich geh mal davon aus dass irgendetwas an deinem Server nicht passt, bzw. nicht richtig lädt. Da du wie in #5 hier auch ständig die Fehlermeldung bekommst: `SERVER: Unknown Command`. Dein server.log kann hier vielleicht Aufschluss geben.

**Comment by DJNK01** [comment]
[server_log.txt](https://github.com/nSystemz/Nemesus-Roleplay/files/9389428/server_log.txt)

**Comment by Spaex** [comment]
Du musst auch die Custom Objekte mit reinladen. Ansonsten werden ggf. Gebäude nicht vollständig angezeigt.
