### ISSUE TITLE
Das Interior vom POD ist unvollständig!

### ISSUE THREAD

**Issue by Justin211098** [nSystemz/Nemesus-Roleplay-Legacy#9]
Guten Tag,

das Interior von der Fraktion POD ist unvollständig. Er lädt nur ein paar Objekte. Wurde die Map mit Absicht entfernt?

**Comment by Spaex** [comment]
Hi, ich glaub das Verwaltungsgebäude was du meinst wurde mal entfernt da es nicht mehr gebraucht wurde oder es wurde nie fertig gestellt. Da kann ich mich aber nicht mehr ganz dran erinnern. Ich glaub auch nicht dass das Nemesus noch hat. Man könnte alternativ einfach das Exterior vom POD nutzen. Da hat man ja auch Büroräumlichkeiten und Co.. Dementsprechend müsste man einfach nur den Duty-Punkt und den Ausrüstpunkt in z.B. die Garage oder Büroräumlichkeiten auf der Westseite des Geländes packen.

**Comment by Justin211098** [comment]
Das Exterior ist dann der Ort wo die Abgeschleppten Autos stehen richtig? Oder gibt es da noch etwas?

**Comment by Spaex** [comment]
![sa-mp-456](https://user-images.githubusercontent.com/46825907/189545023-88e020bf-38a5-4d3f-9e3e-99886d76450c.png)

Das sind die 3 Verwahrhallen, es gibt auch noch die Werkstatt + Büro Räumlichkeiten. Siehe Screenshot.
